### ISSUE TITLE
Results should include browser name

### ISSUE THREAD

**Issue by stanislavgeorgiev** [tanenbaum/karma-json-result-reporter#1]
Hi, I like the plugin and it's just the thing I needed. However, I'm running tests in Chrome and IE and the results file doesn't include the browser in which the test was run in:

```
{
    "errors": [],
    "results": [
        {
            "description": "should say Hello to the World",
            "id": "spec0",
            "log": [],
            "skipped": false,
            "success": true,
            "suite": [
                "greeter"
            ],
            "time": 0,
            "executedExpectationsCount": 1
        },
        {
            "description": "should say Hello to the World",
            "id": "spec0",
            "log": [],
            "skipped": false,
            "success": true,
            "suite": [
                "greeter"
            ],
            "time": 2,
            "executedExpectationsCount": 1
        }
    ]
}
```

**Comment by tanenbaum** [comment]
I'm glad you're finding it useful. 

You're absolutely right, it does need results sets per browser. I was using it primarily for single phantom runs so it hadn't occurred to me.

It won't be difficult to accomplish. Do you have a schema in mind?

**Comment by tanenbaum** [comment]
JSON output changed to be browser centric in v1.0.0.

**Comment by stanislavgeorgiev** [comment]
Hey, no worries and thanks for the quick fix!
